package atamayo.offlinereddit.RedditDAO;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import atamayo.offlinereddit.RedditAPI.RedditThread;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "REDDIT_THREADS".
*/
public class RedditThreadDao extends AbstractDao<RedditThread, Long> {

    public static final String TABLENAME = "REDDIT_THREADS";

    /**
     * Properties of entity RedditThread.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Filename = new Property(1, String.class, "filename", false, "FILENAME");
        public final static Property WasClicked = new Property(2, boolean.class, "wasClicked", false, "WAS_CLICKED");
        public final static Property Subreddit = new Property(3, String.class, "subreddit", false, "SUBREDDIT");
        public final static Property Title = new Property(4, String.class, "title", false, "TITLE");
        public final static Property Score = new Property(5, int.class, "score", false, "SCORE");
        public final static Property Ups = new Property(6, int.class, "ups", false, "UPS");
        public final static Property Downs = new Property(7, int.class, "downs", false, "DOWNS");
        public final static Property Permalink = new Property(8, String.class, "permalink", false, "PERMALINK");
        public final static Property NumComments = new Property(9, int.class, "numComments", false, "NUM_COMMENTS");
    }


    public RedditThreadDao(DaoConfig config) {
        super(config);
    }
    
    public RedditThreadDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"REDDIT_THREADS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"FILENAME\" TEXT," + // 1: filename
                "\"WAS_CLICKED\" INTEGER NOT NULL ," + // 2: wasClicked
                "\"SUBREDDIT\" TEXT," + // 3: subreddit
                "\"TITLE\" TEXT," + // 4: title
                "\"SCORE\" INTEGER NOT NULL ," + // 5: score
                "\"UPS\" INTEGER NOT NULL ," + // 6: ups
                "\"DOWNS\" INTEGER NOT NULL ," + // 7: downs
                "\"PERMALINK\" TEXT," + // 8: permalink
                "\"NUM_COMMENTS\" INTEGER NOT NULL );"); // 9: numComments
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_REDDIT_THREADS_TITLE ON REDDIT_THREADS" +
                " (\"TITLE\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"REDDIT_THREADS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, RedditThread entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String filename = entity.getFilename();
        if (filename != null) {
            stmt.bindString(2, filename);
        }
        stmt.bindLong(3, entity.getWasClicked() ? 1L: 0L);
 
        String subreddit = entity.getSubreddit();
        if (subreddit != null) {
            stmt.bindString(4, subreddit);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(5, title);
        }
        stmt.bindLong(6, entity.getScore());
        stmt.bindLong(7, entity.getUps());
        stmt.bindLong(8, entity.getDowns());
 
        String permalink = entity.getPermalink();
        if (permalink != null) {
            stmt.bindString(9, permalink);
        }
        stmt.bindLong(10, entity.getNumComments());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, RedditThread entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String filename = entity.getFilename();
        if (filename != null) {
            stmt.bindString(2, filename);
        }
        stmt.bindLong(3, entity.getWasClicked() ? 1L: 0L);
 
        String subreddit = entity.getSubreddit();
        if (subreddit != null) {
            stmt.bindString(4, subreddit);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(5, title);
        }
        stmt.bindLong(6, entity.getScore());
        stmt.bindLong(7, entity.getUps());
        stmt.bindLong(8, entity.getDowns());
 
        String permalink = entity.getPermalink();
        if (permalink != null) {
            stmt.bindString(9, permalink);
        }
        stmt.bindLong(10, entity.getNumComments());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public RedditThread readEntity(Cursor cursor, int offset) {
        RedditThread entity = new RedditThread( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // filename
            cursor.getShort(offset + 2) != 0, // wasClicked
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // subreddit
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // title
            cursor.getInt(offset + 5), // score
            cursor.getInt(offset + 6), // ups
            cursor.getInt(offset + 7), // downs
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // permalink
            cursor.getInt(offset + 9) // numComments
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, RedditThread entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFilename(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setWasClicked(cursor.getShort(offset + 2) != 0);
        entity.setSubreddit(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTitle(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setScore(cursor.getInt(offset + 5));
        entity.setUps(cursor.getInt(offset + 6));
        entity.setDowns(cursor.getInt(offset + 7));
        entity.setPermalink(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setNumComments(cursor.getInt(offset + 9));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(RedditThread entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(RedditThread entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(RedditThread entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
